fighthealthinsurance/fighthealthinsurance

run_local.sh
This allows *run_local.sh** to run on MacOS as well as aptitude.
=> Update run_local.sh for MacOS use.

fighthealthinsurance/settings.py
=> Disable DEBUG in production

fighthealthinsurance/views.py
This moves all of the simple template rendering views into using **django.views.generic.TemplateView** instead.
=> Use TemplateView when it makes sense

fighthealthinsurance/settings.py
The **Dev** class was using **Debug** instead of **DEBUG** for the setting name
=> Fix DEBUG setting capitalization in Dev environment

fighthealthinsurance/forms.py, fighthealthinsurance/process_denial.py, fighthealthinsurance/settings.py, fighthealthinsurance/templates/appeals.html, fighthealthinsurance/views.py
Fix the JavaScript + AJAX hacks to submit all of the information we care about through.
We use these hacks to get the responses in a non-blocking fashion
=> Fix up the JavaScript + ajax hacks

fighthealthinsurance/models.py, fighthealthinsurance/templates/scrub.html, fighthealthinsurance/urls.py, fighthealthinsurance/views.py, tests/test_core_urls_load.py
Refactoring to conventional view structure
=> Refactoring to conventional view structure

deploy.yaml, fighthealthinsurance/combined_storage.py, fighthealthinsurance/ml_models.py, fighthealthinsurance/models.py, fighthealthinsurance/settings.py, requirements.txt, run_local.sh
When NFS goes sideways and also make storage engine fall through a few different settings
=> Deal with unreliable filesystem

fighthealthinsurance/common_view_logic.py, fighthealthinsurance/generate_appeal.py, fighthealthinsurance/ml_models.py, fighthealthinsurance/utils.py
also improve our ordering so we don't always show the static template results first (folks are biased towards the first result)
=> Improve our external model interface

fighthealthinsurance/templates/index.html, fighthealthinsurance/templates/professional.html
minor typo corrections + improved tone
=> minor improvements to web copy

fighthealthinsurance/templates/index.html
Update text sections on homepage, particularly grammar and misspelling
=> Update homepage text

README.md, fighthealthinsurance/common_view_logic.py, fighthealthinsurance/core_forms.py, fighthealthinsurance/templates/appeal.html, fighthealthinsurance/templates/appeals.html, fighthealthinsurance/templates/categorize.html, fighthealthinsurance/templates/outside_help.html, tests/sync/test_selenium_appeal_generation.py
Includes https://github.com/totallylegitco/fighthealthinsurance/pull/125 + some fixes to the tests
Update categorize::denial flow, add styling
Edit some label questions
Minor wording fixes, will need to revisit
Update update::denial flow, add styling into html ele - will revisit …
last page for generating an appeal needs further work. complete page restructure, but revisit to work out styling
done by [jfang5792](https://github.com/jfang5792)
=> Rest of Appeal workflow

README.md, fighthealthinsurance/core_forms.py, fighthealthinsurance/static/css/custom.css, fighthealthinsurance/static/css/main.css, fighthealthinsurance/static/js/scrub.ts, fighthealthinsurance/templates/appeal.html, fighthealthinsurance/templates/scrub.html, fighthealthinsurance/views.py
- Clean up some CSS
- Try and make the workflow a bit clearer when folks leave stuff off
=> More clean up & slight workflow improvement

build.sh, cluster.yaml, deploy.yaml, fighthealthinsurance/fax_actor.py, fighthealthinsurance/templates/emails/fax_followup.html, fighthealthinsurance/templates/emails/fax_followup.txt
We were getting some annoying django errors even using async for, asave, and aget. Given current volume it's better to just use sync and revisit async later.
=> Remove async from the fax actor

build.sh, cluster.yaml, deploy.yaml, fighthealthinsurance/static/js/scrub.ts, fighthealthinsurance/templates/scrub.html
- Avoid submit on scrub button (it didn't actually submit anything since you had to agree to TOS first anyways but eh error messages were confusing as a result)
- Hide error messages as the errors are corrected
- Fall through on PDF/Image processing since mime type inference is imperfect.
=> Improve scrub typescript

fighthealthinsurance/templates/scrub.html
Not passing test spec - def test_server_side_ocr_workflow(self)
this part:
```
self.assert_text(
"""UnidentifiedImageError""",
"textarea#denial_text",
)
```
=> create text descriptions of each section in initial denial upload

fighthealthinsurance/static/css/custom.css, fighthealthinsurance/templates/remove_data.html, fighthealthinsurance/templates/removed_data.html
Change GET msg to ask for email inputted prior
Change POST msg to say any data 'associated'...
Create gradient submit button
Add border box to header / minimal styling for now until we decide on a new logo and background
Create new styling elements: .delete-header and .btn-delete
=> Delete Your Data UI fixes

fighthealthinsurance/templates/about_us.html
Fixed contraction to that of intended possessive.
=> Fixes contraction grammar typo.

fighthealthinsurance/static/css/custom.css, fighthealthinsurance/templates/base.html, fighthealthinsurance/templates/contact.html, fighthealthinsurance/templates/index.html
Improve homepage a little, upgrade that UI yo
=> Improve homepage UI

.github/workflows/ci.yml, k8s/deploy.yaml, k8s/ray/cluster.yaml, scripts/build.sh, scripts/check_shell_style.sh, scripts/fetch_data.sh, scripts/run_local.sh, scripts/start-server.sh
- Use envsubst on the yaml files
- Cleanup some of the scripts with shellcheck
=> Improve deployment a little bit

fighthealthinsurance/static/js/appeal_fetcher.ts, fighthealthinsurance/static/js/appel_fetcher.ts, fighthealthinsurance/static/js/tsconfig.json, fighthealthinsurance/static/js/webpack.config.js, fighthealthinsurance/templates/appeals.html
Make the appeal fetcher script retry a few different errors
Move it to type script
=> Fix appeal with retry

fighthealthinsurance/asgi.py, fighthealthinsurance/urls.py, fighthealthinsurance/wsgi.py, requirements.txt, scripts/start-server.sh
We need to add testing that the container actually launches as desired to the GHA
=> Switch to ASGI with uvicorn

fighthealthinsurance/static/css/custom.css, fighthealthinsurance/templates/professional.html, fighthealthinsurance/templates/scrub.html
Update CSS to add together-form-group for when we want things ~together vertically on desktop and spaced on mobile
=> Improve mobile & desktop grouping of form elements

tests/async/test_rest_api.py
Addresses #111 
Not sure at the moment if stronger assertions are required and whether we have a preference for `self.assertXYZ` style assertions or `assert foo=bar` style assertions
=> Added assertion to test, removed global import

fighthealthinsurance/templates/base.html, fighthealthinsurance/templates/remove_data.html
- Took out footer copyright text
- commented out anchor scroll up logo for now since it's not functional
- open external tab for donation
- fix spacing in text on delete page
TODO: override bootstrap width 100% with style="max-width:none;width: auto;
=> Updates to base footer and delete page

fhi_users/auth/auth_utils.py, fhi_users/auth/rest_auth_views.py, fhi_users/urls.py, fighthealthinsurance/management/commands/make_user.py, fighthealthinsurance/rest_serializers.py, fighthealthinsurance/settings.py, requirements.txt, scripts/build_openapidocs.sh
Fix creation of the test user for local dev
Automate documention of rest APIs fix some misc bugs
=> Fix creation of test user for local dev + misc fixes

fighthealthinsurance/rest_serializers.py, fighthealthinsurance/rest_views.py
and add some filters (not yet handled) for appeal list endpoint
=> Remove duplicated filter_to_allowed_appeals logic
